#ifndef IBMBRUTE_GUI_RESOURCES_H
#define IBMBRUTE_GUI_RESOURCES_H

#define IDD_MAIN_DIALOG 101

#define IDC_GPU_COMBO 1001
#define IDC_CONFIGURE_BUTTON 1002
#define IDC_USERNAME_EDIT 1003
#define IDC_HASH_EDIT 1004
#define IDC_PROGRESS_BAR 1005
#define IDC_CRACK_BUTTON 1006

#endif
